### ISSUE TITLE
Looking for ADAU1761 init sequence for Marshall Acton 2

### ISSUE THREAD

**Issue by timtashpulatov** [hamoonzehzad/MarshallActon2#1]
Hello, is this an alternative configuration for ADAU1761 codec in Marshall Acton 2? I am working on a custom firmware for the said speaker.

**Comment by hamoonzehzad** [comment]
Hey @timtashpulatov 
This is just a simple application for keep the speaker connected. As you may already know one of the major problems that ACTON 2 has is that it goes into the sleep mode after being idle for about 20 minutes. So this application checks the speaker on intervals and checks if there is any problem in the connection via Bluetooth or not. If this is the case then it will try to reconnect the speaker again and therefore prevents the speaker to go to the sleep mode.

**Comment by timtashpulatov** [comment]
Many thanks for prompt reply.

Is this application supposed to run alongside existing configuration of DSP? How do you load it into ADAU? Sorry if this is off topic, I am figuring out the schematic and architecture of fried Acton 2 and at some point will have to write some initialization code for the DSP. As far as I understand one of its analog output mixers feeds the dedicated TPA3118 class D amp for the bass. Thus I suspect the DSP might add certain bass boost functionality.

**Comment by hamoonzehzad** [comment]
@timtashpulatov 

I refactored the application for you so hopefully you can read and understand it more easily. 
This application is just about checking the state of Bluetooth connection and reconnecting the device if it is disconnected using the operating system APIs. 
As you already know every single device has different type of services that are responsible for different functionalities such as audio, video etc. and every single service has its own unique UUID.
First I find the speaker using the Bluetooth client object and then I try to reconnect its services one by one in parallel fashion. 
This application doesn't have anything to do with the low level chipset configuration and it just uses the high level communication APIs provided by the operating system. 
Although this application is written by .NET 8 which is cross-platform but it's worth to mention that it uses just windows APIs to find the Bluetooth devices so you cannot run this application on Mac or Linux.
In order to make it work as a background process I created a windows service which will run this application in the background whenever I logged in in my operating system.

**Comment by timtashpulatov** [comment]
@hamoonzehzad thanks for thorough explanation!
